// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: interact_word.proto
// Protobuf Java Version: 4.32.0

package top.pigest.queuemanagerdemo.liveroom;

@com.google.protobuf.Generated
@SuppressWarnings("all")
public final class InteractWordOuterClass {
  private InteractWordOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      InteractWordOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InteractWordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.pigest.queuemanagerdemo.liveroom.InteractWord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 uid = 1;</code>
     * @return The uid.
     */
    long getUid();

    /**
     * <code>string uname = 2;</code>
     * @return The uname.
     */
    java.lang.String getUname();
    /**
     * <code>string uname = 2;</code>
     * @return The bytes for uname.
     */
    com.google.protobuf.ByteString
        getUnameBytes();

    /**
     * <code>int64 msg_type = 5;</code>
     * @return The msgType.
     */
    long getMsgType();
  }
  /**
   * Protobuf type {@code top.pigest.queuemanagerdemo.liveroom.InteractWord}
   */
  public static final class InteractWord extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:top.pigest.queuemanagerdemo.liveroom.InteractWord)
      InteractWordOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        InteractWord.class.getName());
    }
    // Use InteractWord.newBuilder() to construct.
    private InteractWord(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private InteractWord() {
      uname_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.internal_static_top_pigest_queuemanagerdemo_liveroom_InteractWord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.internal_static_top_pigest_queuemanagerdemo_liveroom_InteractWord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord.class, top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private long uid_ = 0L;
    /**
     * <code>int64 uid = 1;</code>
     * @return The uid.
     */
    @java.lang.Override
    public long getUid() {
      return uid_;
    }

    public static final int UNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object uname_ = "";
    /**
     * <code>string uname = 2;</code>
     * @return The uname.
     */
    @java.lang.Override
    public java.lang.String getUname() {
      java.lang.Object ref = uname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uname_ = s;
        return s;
      }
    }
    /**
     * <code>string uname = 2;</code>
     * @return The bytes for uname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUnameBytes() {
      java.lang.Object ref = uname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 5;
    private long msgType_ = 0L;
    /**
     * <code>int64 msg_type = 5;</code>
     * @return The msgType.
     */
    @java.lang.Override
    public long getMsgType() {
      return msgType_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0L) {
        output.writeInt64(1, uid_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uname_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, uname_);
      }
      if (msgType_ != 0L) {
        output.writeInt64(5, msgType_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uid_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uname_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, uname_);
      }
      if (msgType_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, msgType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord)) {
        return super.equals(obj);
      }
      top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord other = (top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord) obj;

      if (getUid()
          != other.getUid()) return false;
      if (!getUname()
          .equals(other.getUname())) return false;
      if (getMsgType()
          != other.getMsgType()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUid());
      hash = (37 * hash) + UNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUname().hashCode();
      hash = (37 * hash) + MSG_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgType());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code top.pigest.queuemanagerdemo.liveroom.InteractWord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:top.pigest.queuemanagerdemo.liveroom.InteractWord)
        top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.internal_static_top_pigest_queuemanagerdemo_liveroom_InteractWord_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.internal_static_top_pigest_queuemanagerdemo_liveroom_InteractWord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord.class, top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord.Builder.class);
      }

      // Construct using top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        uid_ = 0L;
        uname_ = "";
        msgType_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.internal_static_top_pigest_queuemanagerdemo_liveroom_InteractWord_descriptor;
      }

      @java.lang.Override
      public top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord getDefaultInstanceForType() {
        return top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord.getDefaultInstance();
      }

      @java.lang.Override
      public top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord build() {
        top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord buildPartial() {
        top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord result = new top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.uid_ = uid_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.uname_ = uname_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.msgType_ = msgType_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord) {
          return mergeFrom((top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord other) {
        if (other == top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord.getDefaultInstance()) return this;
        if (other.getUid() != 0L) {
          setUid(other.getUid());
        }
        if (!other.getUname().isEmpty()) {
          uname_ = other.uname_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getMsgType() != 0L) {
          setMsgType(other.getMsgType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                uid_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                uname_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 40: {
                msgType_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long uid_ ;
      /**
       * <code>int64 uid = 1;</code>
       * @return The uid.
       */
      @java.lang.Override
      public long getUid() {
        return uid_;
      }
      /**
       * <code>int64 uid = 1;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(long value) {

        uid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 uid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object uname_ = "";
      /**
       * <code>string uname = 2;</code>
       * @return The uname.
       */
      public java.lang.String getUname() {
        java.lang.Object ref = uname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uname = 2;</code>
       * @return The bytes for uname.
       */
      public com.google.protobuf.ByteString
          getUnameBytes() {
        java.lang.Object ref = uname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uname = 2;</code>
       * @param value The uname to set.
       * @return This builder for chaining.
       */
      public Builder setUname(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        uname_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string uname = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUname() {
        uname_ = getDefaultInstance().getUname();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string uname = 2;</code>
       * @param value The bytes for uname to set.
       * @return This builder for chaining.
       */
      public Builder setUnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        uname_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long msgType_ ;
      /**
       * <code>int64 msg_type = 5;</code>
       * @return The msgType.
       */
      @java.lang.Override
      public long getMsgType() {
        return msgType_;
      }
      /**
       * <code>int64 msg_type = 5;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(long value) {

        msgType_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 msg_type = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgType_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:top.pigest.queuemanagerdemo.liveroom.InteractWord)
    }

    // @@protoc_insertion_point(class_scope:top.pigest.queuemanagerdemo.liveroom.InteractWord)
    private static final top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord();
    }

    public static top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InteractWord>
        PARSER = new com.google.protobuf.AbstractParser<InteractWord>() {
      @java.lang.Override
      public InteractWord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<InteractWord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InteractWord> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public top.pigest.queuemanagerdemo.liveroom.InteractWordOuterClass.InteractWord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_pigest_queuemanagerdemo_liveroom_InteractWord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_top_pigest_queuemanagerdemo_liveroom_InteractWord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023interact_word.proto\022$top.pigest.queuem" +
      "anagerdemo.liveroom\"<\n\014InteractWord\022\013\n\003u" +
      "id\030\001 \001(\003\022\r\n\005uname\030\002 \001(\t\022\020\n\010msg_type\030\005 \001(" +
      "\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_top_pigest_queuemanagerdemo_liveroom_InteractWord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_top_pigest_queuemanagerdemo_liveroom_InteractWord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_top_pigest_queuemanagerdemo_liveroom_InteractWord_descriptor,
        new java.lang.String[] { "Uid", "Uname", "MsgType", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
